In [1]:
import pandas as pd

In [3]:
data=pd.read_csv(r"C:\Users\dell\Downloads\car data.csv")

In [4]:
data

           Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
13       Honda       Civic    1600    1252   94
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
20        Ford      Mondeo    1600    1584   94
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

In [5]:
data.head()

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [6]:
data.shape

(36, 5)

In [7]:
# data cleaning
# find al null values and in case null values fill it with mean of that column
data.isnull().sum()
# no null values data.["cylinder"].fillna(data['cylinder"].mean(),inplace=True)

Car       0
Model     0
Volume    0
Weight    0
CO2       0
dtype: int64

In [8]:
# check wht are differeent types of make are there in data and what is the count of each make?
data.head(2)

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95

In [11]:
data["Car"].value_counts()

Car
Ford          5
Mercedes      5
Skoda         4
Volvo         3
Audi          3
BMW           3
Opel          3
Toyoty        1
Mini          1
VW            1
Mitsubishi    1
Fiat          1
Hyundai       1
Hundai        1
Honda         1
Suzuki        1
Mazda         1
Name: count, dtype: int64

In [12]:
# remove unwanted records with weight above 4000
data.head(2)

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95

In [17]:
data[~(data["Weight"]> 2000)]

           Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
13       Honda       Civic    1600    1252   94
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
20        Ford      Mondeo    1600    1584   94
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

In [19]:
# increase all the values of a column by 3
data["CO2"]=data["CO2"].apply(lambda x:x+3)

In [20]:
data

           Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790  105
1   Mitsubishi  Space Star    1200    1160  101
2        Skoda      Citigo    1000     929  101
3         Fiat         500     900     865   96
4         Mini      Cooper    1500    1140  111
5           VW         Up!    1000     929  111
6        Skoda       Fabia    1400    1109   96
7     Mercedes     A-Class    1500    1365   98
8         Ford      Fiesta    1500    1112  104
9         Audi          A1    1600    1150  105
10     Hyundai         I20    1100     980  105
11      Suzuki       Swift    1300     990  107
12        Ford      Fiesta    1000    1112  105
13       Honda       Civic    1600    1252  100
14      Hundai         I30    1600    1326  103
15        Opel       Astra    1600    1330  103
16         BMW           1    1600    1365  105
17       Mazda           3    2200    1280  110
18       Skoda       Rapid    1600    1119  110
19        Ford       Focus    2000    1328  111
20        Ford      Mondeo    1600    1584  100
21        Opel    Insignia    2000    1428  105
22    Mercedes     C-Class    2100    1365  105
23       Skoda     Octavia    1600    1415  105
24       Volvo         S60    2000    1415  105
25    Mercedes         CLA    1500    1465  108
26        Audi          A4    2000    1490  110
27        Audi          A6    2000    1725  120
28       Volvo         V70    1600    1523  115
29         BMW           5    2000    1705  120
30    Mercedes     E-Class    2100    1605  121
31       Volvo        XC70    2000    1746  123
32        Ford       B-Max    1600    1235  110
33         BMW         216    1600    1390  114
34        Opel      Zafira    1600    1405  115
35    Mercedes         SLK    2500    1395  126