In [1]:
import pandas as pd

In [3]:
data=pd.read_csv(r"C:\Users\dell\Downloads\weather.csv")

In [4]:
data

,Data.Precipitation,Date.Full,Date.Month,Date.Week of,Date.Year,Station.City,Station.Code,Station.Location,Station.State,Data.Temperature.Avg Temp,Data.Temperature.Max Temp,Data.Temperature.Min Temp,Data.Wind.Direction,Data.Wind.Speed
0,0.00,2016-01-03,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,2016-01-03,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,2016-01-03,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,2016-01-03,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,2016-01-03,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16738,0.08,2017-01-01,1,1,2017,Casper,CPR,"Casper, WY",Wyoming,23,32,15,23,19.98
16739,0.00,2017-01-01,1,1,2017,Cheyenne,CYS,"Cheyenne, WY",Wyoming,32,42,21,26,15.16
16740,0.00,2017-01-01,1,1,2017,Lander,LND,"Lander, WY",Wyoming,17,29,4,26,1.65
16741,0.06,2017-01-01,1,1,2017,Rawlins,RWL,"Rawlins, WY",Wyoming,23,31,13,24,18.16
16742,0.10,2017-01-01,1,1,2017,Sheridan,SHR,"Sheridan, WY",Wyoming,21,34,8,23,7.51

In [5]:
data.head()

,Data.Precipitation,Date.Full,Date.Month,Date.Week of,Date.Year,Station.City,Station.Code,Station.Location,Station.State,Data.Temperature.Avg Temp,Data.Temperature.Max Temp,Data.Temperature.Min Temp,Data.Wind.Direction,Data.Wind.Speed
0,0.00,2016-01-03,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,2016-01-03,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,2016-01-03,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,2016-01-03,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,2016-01-03,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80

In [7]:
data.shape

(16743, 14)

In [8]:
data.index

RangeIndex(start=0, stop=16743, step=1)

In [9]:
data.columns

Index(['Data.Precipitation', 'Date.Full', 'Date.Month', 'Date.Week of',
       'Date.Year', 'Station.City', 'Station.Code', 'Station.Location',
       'Station.State', 'Data.Temperature.Avg Temp',
       'Data.Temperature.Max Temp', 'Data.Temperature.Min Temp',
       'Data.Wind.Direction', 'Data.Wind.Speed'],
      dtype='object')

In [10]:
data.dtypes

Data.Precipitation           float64
Date.Full                     object
Date.Month                     int64
Date.Week of                   int64
Date.Year                      int64
Station.City                  object
Station.Code                  object
Station.Location              object
Station.State                 object
Data.Temperature.Avg Temp      int64
Data.Temperature.Max Temp      int64
Data.Temperature.Min Temp      int64
Data.Wind.Direction            int64
Data.Wind.Speed              float64
dtype: object

In [18]:
data['Station.State'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'DE', 'Delaware', 'Florida', 'Georgia',
       'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'VA', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
       'Wisconsin', 'Wyoming'], dtype=object)

In [19]:
data.nunique()

Data.Precipitation            565
Date.Full                      53
Date.Month                     12
Date.Week of                   31
Date.Year                       2
Station.City                  307
Station.Code                  318
Station.Location              318
Station.State                  53
Data.Temperature.Avg Temp     119
Data.Temperature.Max Temp     125
Data.Temperature.Min Temp     114
Data.Wind.Direction            37
Data.Wind.Speed              1461
dtype: int64

In [20]:
data.count

<bound method DataFrame.count of        Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
0                    0.00  2016-01-03           1             3       2016
1                    0.00  2016-01-03           1             3       2016
2                    0.16  2016-01-03           1             3       2016
3                    0.00  2016-01-03           1             3       2016
4                    0.01  2016-01-03           1             3       2016
...                   ...         ...         ...           ...        ...
16738                0.08  2017-01-01           1             1       2017
16739                0.00  2017-01-01           1             1       2017
16740                0.00  2017-01-01           1             1       2017
16741                0.06  2017-01-01           1             1       2017
16742                0.10  2017-01-01           1             1       2017

      Station.City Station.Code Station.Location Station.State  \
0       Birmingham          BHM   Birmingham, AL       Alabama
1       Huntsville          HSV   Huntsville, AL       Alabama
2           Mobile          MOB       Mobile, AL       Alabama
3       Montgomery          MGM   Montgomery, AL       Alabama
4        Anchorage          ANC    Anchorage, AK        Alaska
...            ...          ...              ...           ...
16738       Casper          CPR       Casper, WY       Wyoming
16739     Cheyenne          CYS     Cheyenne, WY       Wyoming
16740       Lander          LND       Lander, WY       Wyoming
16741      Rawlins          RWL      Rawlins, WY       Wyoming
16742     Sheridan          SHR     Sheridan, WY       Wyoming

       Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
0                             39                         46
1                             39                         47
2                             46                         51
3                             45                         52
4                             34                         38
...                          ...                        ...
16738                         23                         32
16739                         32                         42
16740                         17                         29
16741                         23                         31
16742                         21                         34

       Data.Temperature.Min Temp  Data.Wind.Direction  Data.Wind.Speed
0                             32                   33             4.33
1                             31                   32             3.86
2                             41                   35             9.73
3                             38                   32             6.86
4                             29                   19             7.80
...                          ...                  ...              ...
16738                         15                   23            19.98
16739                         21                   26            15.16
16740                          4                   26             1.65
16741                         13                   24            18.16
16742                          8                   23             7.51

[16743 rows x 14 columns]>

In [21]:
data.value_counts

<bound method DataFrame.value_counts of        Data.Precipitation   Date.Full  Date.Month  Date.Week of  Date.Year  \
0                    0.00  2016-01-03           1             3       2016
1                    0.00  2016-01-03           1             3       2016
2                    0.16  2016-01-03           1             3       2016
3                    0.00  2016-01-03           1             3       2016
4                    0.01  2016-01-03           1             3       2016
...                   ...         ...         ...           ...        ...
16738                0.08  2017-01-01           1             1       2017
16739                0.00  2017-01-01           1             1       2017
16740                0.00  2017-01-01           1             1       2017
16741                0.06  2017-01-01           1             1       2017
16742                0.10  2017-01-01           1             1       2017

      Station.City Station.Code Station.Location Station.State  \
0       Birmingham          BHM   Birmingham, AL       Alabama
1       Huntsville          HSV   Huntsville, AL       Alabama
2           Mobile          MOB       Mobile, AL       Alabama
3       Montgomery          MGM   Montgomery, AL       Alabama
4        Anchorage          ANC    Anchorage, AK        Alaska
...            ...          ...              ...           ...
16738       Casper          CPR       Casper, WY       Wyoming
16739     Cheyenne          CYS     Cheyenne, WY       Wyoming
16740       Lander          LND       Lander, WY       Wyoming
16741      Rawlins          RWL      Rawlins, WY       Wyoming
16742     Sheridan          SHR     Sheridan, WY       Wyoming

       Data.Temperature.Avg Temp  Data.Temperature.Max Temp  \
0                             39                         46
1                             39                         47
2                             46                         51
3                             45                         52
4                             34                         38
...                          ...                        ...
16738                         23                         32
16739                         32                         42
16740                         17                         29
16741                         23                         31
16742                         21                         34

       Data.Temperature.Min Temp  Data.Wind.Direction  Data.Wind.Speed
0                             32                   33             4.33
1                             31                   32             3.86
2                             41                   35             9.73
3                             38                   32             6.86
4                             29                   19             7.80
...                          ...                  ...              ...
16738                         15                   23            19.98
16739                         21                   26            15.16
16740                          4                   26             1.65
16741                         13                   24            18.16
16742                          8                   23             7.51

[16743 rows x 14 columns]>

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16743 entries, 0 to 16742
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Data.Precipitation         16743 non-null  float64
 1   Date.Full                  16743 non-null  object
 2   Date.Month                 16743 non-null  int64
 3   Date.Week of               16743 non-null  int64
 4   Date.Year                  16743 non-null  int64
 5   Station.City               16743 non-null  object
 6   Station.Code               16743 non-null  object
 7   Station.Location           16743 non-null  object
 8   Station.State              16743 non-null  object
 9   Data.Temperature.Avg Temp  16743 non-null  int64
 10  Data.Temperature.Max Temp  16743 non-null  int64
 11  Data.Temperature.Min Temp  16743 non-null  int64
 12  Data.Wind.Direction        16743 non-null  int64
 13  Data.Wind.Speed            16743 non-null  float64
dtypes: float64(2), int64(7), object(5)
memory usage: 1.8+ MB

In [29]:
#find all the unique wind speed values in data

data["Data.Wind.Speed"].nunique()

1461

In [28]:
data["Data.Wind.Speed"].unique()

array([ 4.33,  3.86,  9.73, ..., 12.53, 19.98, 18.16], shape=(1461,))

In [31]:
#find the number of times when the wind speed was 4km/h
#data.head(2)
data[data["Data.Wind.Speed"]==4]

,Data.Precipitation,Date.Full,Date.Month,Date.Week of,Date.Year,Station.City,Station.Code,Station.Location,Station.State,Data.Temperature.Avg Temp,Data.Temperature.Max Temp,Data.Temperature.Min Temp,Data.Wind.Direction,Data.Wind.Speed
232,0.01,2016-01-03,1,3,2016,Pendleton,PDT,"Pendleton, OR",Oregon,19,20,17,12,4.0
531,0.05,2016-01-10,1,10,2016,Williston,ISN,"Williston, ND",North Dakota,10,20,3,21,4.0
1155,0.96,2016-01-24,1,24,2016,Raleigh/Durham,RDU,"Raleigh/Durham, NC",North Carolina,30,37,23,23,4.0
2572,0.06,2016-02-28,2,28,2016,Red Bluff,RBL,"Red Bluff, CA",California,56,68,43,31,4.0
2648,1.68,2016-02-28,2,28,2016,Slidell,ASD,"Slidell, LA",Louisiana,55,67,43,17,4.0
4331,0.00,2016-04-03,4,3,2016,Pendleton,PDT,"Pendleton, OR",Oregon,58,73,42,17,4.0
5307,0.22,2016-04-24,4,24,2016,Nashville,BNA,"Nashville, TN",Tennessee,67,80,53,24,4.0
5515,0.00,2016-05-01,5,1,2016,Greenville,GLH,"Greenville, MS",Mississippi,75,84,66,14,4.0
6000,0.10,2016-05-15,5,15,2016,Anchorage,ANC,"Anchorage, AK",Alaska,55,64,45,19,4.0
6297,0.04,2016-05-15,5,15,2016,Seattle,SEA,"Seattle, WA",Washington,60,70,49,20,4.0
6335,0.56,2016-05-22,5,22,2016,Mc Grath,MCG,"Mc Grath, AK",Alaska,47,55,39,17,4.0
6820,0.02,2016-05-29,5,29,2016,Reno,RNO,"Reno, NV",Nevada,60,74,46,28,4.0
6885,2.17,2016-05-29,5,29,2016,Sioux Falls,FSD,"Sioux Falls, SD",South Dakota,67,77,57,14,4.0
6897,1.08,2016-05-29,5,29,2016,Austin/City,ATT,"Austin/City, TX",Texas,78,86,70,14,4.0
7880,0.14,2016-06-19,6,19,2016,Yakima,YKM,"Yakima, WA",Washington,58,73,42,26,4.0
8630,3.33,2016-07-10,7,10,2016,Evansville,EVV,"Evansville, IN",Indiana,78,86,70,21,4.0
9338,0.00,2016-07-24,7,24,2016,Eureka,P68,"Eureka, NV",Nevada,70,94,46,20,4.0
10150,0.00,2016-08-14,8,14,2016,Long Beach,LGB,"Long Beach, CA",California,74,82,66,26,4.0
11248,0.00,2016-09-04,9,4,2016,Albany,ALB,"Albany, NY",New York,67,78,56,27,4.0
11255,0.00,2016-09-04,9,4,2016,Syracuse,SYR,"Syracuse, NY",New York,65,76,53,26,4.0
12458,0.24,2016-10-02,10,2,2016,Lansing,LAN,"Lansing, MI",Michigan,59,68,50,18,4.0
12460,0.31,2016-10-02,10,2,2016,Muskegon,MKG,"Muskegon, MI",Michigan,61,69,53,19,4.0
12512,0.00,2016-10-02,10,2,2016,Roswell,ROW,"Roswell, NM",New Mexico,69,86,52,19,4.0
12684,0.00,2016-10-09,10,9,2016,Los Angeles,LAX,"Los Angeles, CA",California,69,78,60,25,4.0
13140,0.03,2016-10-16,10,16,2016,Concord,CON,"Concord, NH",New Hampshire,49,64,33,21,4.0
13311,0.00,2016-10-23,10,23,2016,Bishop,BIH,"Bishop, CA",California,58,78,38,27,4.0
13710,0.00,2016-10-30,10,30,2016,New Orleans,MSY,"New Orleans, LA",Louisiana,74,84,64,6,4.0
14411,0.00,2016-11-13,11,13,2016,Roswell,ROW,"Roswell, NM",New Mexico,54,67,40,22,4.0
14694,0.38,2016-11-20,11,20,2016,Billings,BIL,"Billings, MT",Montana,38,46,31,16,4.0
14827,3.17,2016-11-20,11,20,2016,Quillayute,UIL,"Quillayute, WA",Washington,46,52,39,12,4.0
14967,0.60,2016-11-27,11,27,2016,Paducah,PAH,"Paducah, KY",Kentucky,44,53,34,13,4.0
15458,2.84,2016-12-04,12,4,2016,Quillayute,UIL,"Quillayute, WA",Washington,43,48,38,21,4.0
16478,0.50,2017-01-01,1,1,2017,Long Beach,LGB,"Long Beach, CA",California,59,69,48,25,4.0

In [32]:
# find out all the null values
data.isnull()

,Data.Precipitation,Date.Full,Date.Month,Date.Week of,Date.Year,Station.City,Station.Code,Station.Location,Station.State,Data.Temperature.Avg Temp,Data.Temperature.Max Temp,Data.Temperature.Min Temp,Data.Wind.Direction,Data.Wind.Speed
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16738,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16739,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16740,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16741,False,False,False,False,False,False,False,False,False,False,False,False,False,False
16742,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [34]:
data.isnull().sum()

Data.Precipitation           0
Date.Full                    0
Date.Month                   0
Date.Week of                 0
Date.Year                    0
Station.City                 0
Station.Code                 0
Station.Location             0
Station.State                0
Data.Temperature.Avg Temp    0
Data.Temperature.Max Temp    0
Data.Temperature.Min Temp    0
Data.Wind.Direction          0
Data.Wind.Speed              0
dtype: int64

In [35]:
data.notnull().sum()

Data.Precipitation           16743
Date.Full                    16743
Date.Month                   16743
Date.Week of                 16743
Date.Year                    16743
Station.City                 16743
Station.Code                 16743
Station.Location             16743
Station.State                16743
Data.Temperature.Avg Temp    16743
Data.Temperature.Max Temp    16743
Data.Temperature.Min Temp    16743
Data.Wind.Direction          16743
Data.Wind.Speed              16743
dtype: int64

In [36]:
# rename the column name 
data.rename(columns={"Data.Wind.Speed":"Speed"})

,Data.Precipitation,Date.Full,Date.Month,Date.Week of,Date.Year,Station.City,Station.Code,Station.Location,Station.State,Data.Temperature.Avg Temp,Data.Temperature.Max Temp,Data.Temperature.Min Temp,Data.Wind.Direction,Speed
0,0.00,2016-01-03,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,2016-01-03,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,2016-01-03,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73
3,0.00,2016-01-03,1,3,2016,Montgomery,MGM,"Montgomery, AL",Alabama,45,52,38,32,6.86
4,0.01,2016-01-03,1,3,2016,Anchorage,ANC,"Anchorage, AK",Alaska,34,38,29,19,7.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16738,0.08,2017-01-01,1,1,2017,Casper,CPR,"Casper, WY",Wyoming,23,32,15,23,19.98
16739,0.00,2017-01-01,1,1,2017,Cheyenne,CYS,"Cheyenne, WY",Wyoming,32,42,21,26,15.16
16740,0.00,2017-01-01,1,1,2017,Lander,LND,"Lander, WY",Wyoming,17,29,4,26,1.65
16741,0.06,2017-01-01,1,1,2017,Rawlins,RWL,"Rawlins, WY",Wyoming,23,31,13,24,18.16
16742,0.10,2017-01-01,1,1,2017,Sheridan,SHR,"Sheridan, WY",Wyoming,21,34,8,23,7.51

In [45]:
data.rename(columns={"Data.Wind.Speed":"Speed"},inplace=True)

In [46]:
#what is the mean of data.avg temp?
#data.head(2)
data.Speed.mean()

np.float64(6.3298202233769345)

In [47]:
#what is standard deviation of speed
data.Speed.std()

np.float64(3.4947852525194727)

In [48]:
# what is the variance of speed
data.Speed.var()

np.float64(12.213523961227596)

In [49]:
data.head(3)

,Data.Precipitation,Date.Full,Date.Month,Date.Week of,Date.Year,Station.City,Station.Code,Station.Location,Station.State,Data.Temperature.Avg Temp,Data.Temperature.Max Temp,Data.Temperature.Min Temp,Data.Wind.Direction,Speed
0,0.00,2016-01-03,1,3,2016,Birmingham,BHM,"Birmingham, AL",Alabama,39,46,32,33,4.33
1,0.00,2016-01-03,1,3,2016,Huntsville,HSV,"Huntsville, AL",Alabama,39,47,31,32,3.86
2,0.16,2016-01-03,1,3,2016,Mobile,MOB,"Mobile, AL",Alabama,46,51,41,35,9.73

In [55]:
# find all inctances when speed is above 6 and avg temperature is 35
data[(data["Speed"] >6) & (data["Data.Temperature.Avg Temp"] ==35)]

,Data.Precipitation,Date.Full,Date.Month,Date.Week of,Date.Year,Station.City,Station.Code,Station.Location,Station.State,Data.Temperature.Avg Temp,Data.Temperature.Max Temp,Data.Temperature.Min Temp,Data.Wind.Direction,Speed
104,0.00,2016-01-03,1,3,2016,Evansville,EVV,"Evansville, IN",Indiana,35,43,27,27,6.06
121,0.00,2016-01-03,1,3,2016,Lexington,LEX,"Lexington, KY",Kentucky,35,42,27,25,7.93
162,0.00,2016-01-03,1,3,2016,Springfield,SGF,"Springfield, MO",Missouri,35,45,23,28,7.50
225,0.00,2016-01-03,1,3,2016,Oklahoma City,OKC,"Oklahoma City, OK",Oklahoma,35,46,24,30,7.16
333,0.04,2016-01-10,1,10,2016,King Salmon,AKN,"King Salmon, AK",Alaska,35,41,29,8,14.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16528,0.44,2017-01-01,1,1,2017,Peoria,PIA,"Peoria, IL",Illinois,35,43,27,24,9.01
16537,0.00,2017-01-01,1,1,2017,Des Moines,DSM,"Des Moines, IA",Iowa,35,44,25,26,11.45
16563,0.95,2017-01-01,1,1,2017,Milton,MQE,"Milton, MA",Massachusetts,35,43,26,21,11.70
16631,0.22,2017-01-01,1,1,2017,Rochester,ROC,"Rochester, NY",New York,35,42,27,24,11.76
16650,0.77,2017-01-01,1,1,2017,Toledo,TOL,"Toledo, OH",Ohio,35,42,28,23,12.06

In [61]:

data.groupby("Station.State").mean()

TypeError: agg function failed [how->mean,dtype->object]